channels:
  - conda-forge
dependencies:
  - cvxopt
  - deepdish
  - discretize
  - empymod
  - git
  - ipywidgets
  - jupyter
  - mkl
  - numpy
  - pandas
  - pillow
  - pip
  - pydiso
  - pymatsolver
  - python
  - requests
  - scipy
  - setuptools
  - simpeg
  - sympy
  - pip:
    - nbconvert[webpdf]
    - git+https://github.com/geoscixyz/geosci-labs
